version: 2
jobs:
  build:
    working_directory: /go/src/github.com/berquerant/circle
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: env
          command: go env
      - run:
          name: test
          command: go test -v -race -cover
